

export const FETCH_MOVIE_DETAIL = "FETCH_MOVIE_DETAIL";
export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const FETCH_CINEMA = "FETCH_CINEMA";
export const FETCH_CINEMA_GROUP = "FETCH_CINEMA_GROUP";
export const CHANGE_ID = "CHANGE_ID";
export const CHECK_SEAT_BOOKING = "CHECK_SEAT_BOOKING";
export const LST_MOVIE = "LST_MOVIE";
export const ADD_MOVIEBOOKING_INFO_PROM_PAYLIST = "ADD_MOVIEBOOKING_INFO_PROM_PAYLIST";
export const LSTBOOKING_TO_SEATLST = "LSTBOOKING_TO_SEATLST";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";






